version: '3.2'

services:
  portainer:
    image: portainer/portainer-ce
    # ports:
    #   - "9000:9000"
    #   - "8000:8000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy_network

volumes:
  portainer_data:
